config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles, only: [:index]
  resources :searches, only: [:index] do
    collection do
      get 'user_history'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  ###################### validations ######################
  validates :title, presence: true
  validates :content, presence: true

  ###################### scopes ######################
  scope :by_title, ->(search) { where("title LIKE ?", "%#{search}%") }
end

app/models/search.rb
class Search < ApplicationRecord
  ###################### validations ######################
  validates :query, presence: true

  ###################### associations ######################
  belongs_to :user

  ###################### hooks ######################
  after_commit :broadcast_most_searched_update

  ###################### scopes ######################
  scope :most_searched, lambda {
    select('query, COUNT(*) as count')
      .group(:query)
      .order(Arel.sql('COUNT(*) DESC'))
      .limit(10)
  }

  ###################### methods ######################
  def self.create_or_update_search(user, query)
    extend SearchHelper

    sanitized_current_query = sanitize_and_downcase_query(query)
    last_search = user.searches.order(created_at: :desc).first
    sanitized_last_search = sanitize_and_downcase_query(last_search&.query)

    if last_search.present? && similar_query?(sanitized_last_search, sanitized_current_query)
      last_search.update(query: query)
    else
      user.searches.create(query: query)
    end
  end

  private

  def broadcast_most_searched_update
    Turbo::StreamsChannel.broadcast_update_to(
      'most_searched',
      target: 'most_searched',
      partial: 'searches/search',
      locals: { searches: self.class.most_searched }
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  ###### validations ######
  validates :ip_address, presence: true, uniqueness: true

  ###### associations ######
  has_many :searches, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    ip = request.headers['X-Forwarded-For']&.split(',')&.first&.strip || request.remote_ip

    @current_user ||= User.find_or_create_by(ip_address: ip)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = filtered_articles
  end

  private

  def filtered_articles
    if params[:search].present?
      Search.create_or_update_search(current_user, params[:search])
      Article.by_title(params[:search])
    else
      Article.all
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @most_searched = Search.most_searched
  end

  def user_history
    @searches = current_user.searches.order(updated_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
  include AppConstants

  def similar_query?(string_a, string_b)
    JaroWinkler.distance(string_a, string_b, ignore_case: true) >= AppConstants::SIMILARITY_THRESHOLD
  end

  def sanitize_and_downcase_query(query)
    query&.delete(' ')&.downcase
  end
end

app/views/articles/_articles_list.html.erb
<div class="container mx-auto p-8">
  <ul class="list-none pl-0">
    <% articles.each do |article| %>
      <li class="py-4 border-b border-gray-300">
        <h3 class="text-2xl font-extrabold text-black mb-2"><%= article.title %></h3>
        <p class="text-lg font-bold text-blueblack-900"><%= article.content %></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/articles/index.html.erb
<div class="container mx-auto p-8 bg-gradient-to-r from-blueblack to-gold-500 rounded-lg shadow-xl text-center">
  <h1 class="text-6xl font-extrabold text-white mb-6">Discover Awesome Articles</h1>
  <%= form_with url: articles_path, method: :get, data: { controller: "search", turbo_frame: "search_results", search_target: "form" }, class: "flex space-x-4" do |form| %>
    <%= form.text_field :search, placeholder: "🔍 Search for articles...", data: { action: "keyup->search#perform" }, class: "form-input block w-full px-6 py-4 text-2xl font-semibold bg-gold-600 text-black bg-clip-padding border border-solid border-gold-700 rounded m-0 focus:bg-gold-700 focus:border-black focus:outline-none" %>
  <% end %>

  <turbo-frame id="search_results">
    <%= render partial: "articles_list", locals: { articles: @articles } %>
  </turbo-frame>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>RealtimeSearchBox</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="bg-gradient-to-r from-teal-500 to-pink-900 text-white font-sans">
  <header class="bg-teal-600 text-pink-300 py-6">
    <div class="container mx-auto flex justify-between items-center">
      <h1 class="text-5xl font-extrabold">🌟 Realtime SearchBox</h1>
      <%= render 'shared/navbar' %>
    </div>
  </header>

  <main class="container mx-auto my-10 px-8 py-12 bg-purple-700 text-yellow-300 rounded-lg shadow-2xl">
    <%= yield %>
  </main>
</body>
</html>

app/views/searches/_search.html.erb
<div class="text-center">
  <div class="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-1 gap-4 max-w-3xl mx-auto mt-10">
    <% searches.each do |search| %>
      <div class="bg-gradient-to-r from-teal-500 to-pink-300 text-white shadow-md rounded-lg p-4 mb-4">
        <span class="text-4xl font-bold block mb-2"><%= search.query %></span>
        <% if search.respond_to?(:count) %>
          <span class="bg-green-500 text-white text-sm font-bold px-3 py-1 rounded-full inline-block"><%= search.count %> times</span>
        <% else %>
          <span class="bg-blue-500 text-white text-xl font-bold px-3 py-1 rounded-full inline-block">
            <%= search.updated_at.strftime('%A, %b %d, %Y %I:%M %p') %>
          </span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/searches/index.html.erb
<div class="text-center">
  <h1 class="flex items-center justify-center font-bold text-5xl mb-6">
    🧐 Top Searches 🚀
  </h1>
  <div class="max-w-md mx-auto mt-10">
    <%= turbo_stream_from(:most_searched) %>
    <turbo-frame id="most_searched">
      <% @most_searched.each_with_index do |search, index| %>
        <div class="bg-gradient-to-r from-teal-500 to-pink-300 text-white shadow-md rounded-lg p-4 mb-4">
          <span class="text-4xl font-bold block mb-2">#<%= index + 1 %> <%= search.query %></span>
          <% if search.respond_to?(:count) %>
            <span class="bg-green-500 text-white text-xl font-bold px-3 py-1 rounded-full inline-block"><%= search.count %> times</span>
          <% else %>
            <span class="bg-blue-500 text-white text-xl font-bold px-3 py-1 rounded-full inline-block"><%= search.updated_at %></span>
          <% end %>
        </div>
      <% end %>
    </turbo-frame>
  </div>
</div>

app/views/searches/user_history.html.erb
<div class="text-center">
  <h1 class="flex items-center justify-center font-bold text-5xl mb-6">🕒 Explore Your Search History 📚</h1>
  <div class="max-w-md mx-auto mt-10">
    <%= render partial: "search", locals: { searches: @searches } %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-gradient-to-r from-teal-500 to-gray-300 py-2">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="ml-4 flex items-center space-x-4">
          <%= link_to root_path, class: "text-black-300 hover:text-white text-2xl font-extrabold transition duration-300" do %>
            Home
          <% end %>
          <%= link_to searches_path, class: "text-gold-300 hover:text-white text-2xl font-extrabold transition duration-300" do %>
            Most Searched
          <% end %>
          <%= link_to user_history_searches_path, class: "text-gold-300 hover:text-white text-2xl font-extrabold transition duration-300" do %>
            History
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>